version: "3.3"
services:
  web:
    ports:
      - "9292:9292"
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/usr/src/app:cached
      - ~/.bash_history:/root/.bash_history
    command: sh -c "bundle exec puma"
    environment:
      RACK_ENV: development

